name: GitHub Actions Demo
run-name: testing out GitHub Actions

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted, macOS, X64
    steps:
      - name: test
        run: |
          RESULT: $(python3 main.py)
          echo "RESULT:${RESULT}" >> $GITHUB_ENV


