
name: GitHub Actions Demo
run-name: testing out GitHub Actions

on:
  push:
    branches : 
      main

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: test
        run: |
          A: $(python3 test.py)
          echo "A:${A}" >> $GITHUB_ENV


